In [1]:
import sys
print(sys.executable)

/workspaces/The-Oracle-Of-Harpies/.venv/bin/python

In [2]:
import os

print(os.getcwd())

/workspaces/The-Oracle-Of-Harpies/notebooks

In [3]:
import os

os.listdir()

['harpies_pair_interpretations.csv',
 'harpies_deck.ipynb',
 'harpy_cards.csv',
 'harpy_cards_meanings.csv',
 'harpy_theme_categories.csv',
 'harpy_cards.json',
 'harpy_theme_relationships.csv',
 'harpies_triple_interpretations.csv',
 'oracle_engine.ipynb']

In [4]:
import os

for root, dirs, files in os.walk("/workspaces/The-Oracle-Of-Harpies"):
    for file in files:
        if file.endswith(".csv"):
            print(os.path.join(root, file))

/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-arctan.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-exp2.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-log.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-log1p.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-tan.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-log10.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-arcsin.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-arctanh.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-exp.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-cos.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-expm1.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-arccos.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-log2.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-sinh.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-sin.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-tanh.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-cosh.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-arccosh.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-arcsinh.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/_core/tests/data/umath-validation-set-cbrt.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/philox-testset-1.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/sfc64-testset-1.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/pcg64-testset-1.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/mt19937-testset-2.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/philox-testset-2.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/pcg64dxsm-testset-1.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/pcg64-testset-2.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/mt19937-testset-1.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/sfc64-testset-2.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/numpy/random/tests/data/pcg64dxsm-testset-2.csv
/workspaces/The-Oracle-Of-Harpies/.venv/lib/python3.12/site-packages/tornado/test/csv_translations/fr_FR.csv
/workspaces/The-Oracle-Of-Harpies/notebooks/harpies_pair_interpretations.csv
/workspaces/The-Oracle-Of-Harpies/notebooks/harpy_cards.csv
/workspaces/The-Oracle-Of-Harpies/notebooks/harpy_cards_meanings.csv
/workspaces/The-Oracle-Of-Harpies/notebooks/harpy_theme_categories.csv
/workspaces/The-Oracle-Of-Harpies/notebooks/harpy_theme_relationships.csv
/workspaces/The-Oracle-Of-Harpies/notebooks/harpies_triple_interpretations.csv

In [5]:
import pandas as pd

print("Pandas loaded successfully")

Pandas loaded successfully

In [6]:
import pandas as pd
print(pd.__version__)

3.0.3

In [7]:
import json

with open("../the-oracle-of-harpies/cards.json", "r") as f:
    cards = json.load(f)

print(type(cards))
print(len(cards))

<class 'list'>
21

In [8]:
cards[0]

{'number': 0,
 'title': 'The Pearl',
 'keywords': ['Potential', 'Void', 'Origin'],
 'oracle': 'Trust what is gestating. Not all treasures are meant to be opened at once.',
 'meaning': 'The Pearl represents pure possibility. It is the cosmic egg, the hidden treasure, the self before form. Within the Pearl lies every future choice, challenge, gift, and transformation. When this card appears, you stand at the threshold of becoming.',
 'image': '00-the-pearl.png'}

In [9]:
for card in cards:
    print(card["number"], "-", card["title"])

0 - The Pearl
1 - The Ear
10 - The Wheel
11 - The Mirror
12 - The Bat
13 - The Thorn
14 - The Angel
15 - The Torch
16 - The Lightning
17 - The Starling
18 - The Moon
19 - The Sun
20 - The Well
21 - The Mountain
22 - Atlas
23 - The Hawk
24 - The Storm
25 - The Vulture
26 - The Eye of Horus
27 - The Goat
28 - The Harpy

In [10]:
numbers = sorted(card["number"] for card in cards)
print(numbers)

[0, 1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28]

In [11]:
titles = [card["title"] for card in cards]
print(titles)

['The Pearl', 'The Ear', 'The Wheel', 'The Mirror', 'The Bat', 'The Thorn', 'The Angel', 'The Torch', 'The Lightning', 'The Starling', 'The Moon', 'The Sun', 'The Well', 'The Mountain', 'Atlas', 'The Hawk', 'The Storm', 'The Vulture', 'The Eye of Horus', 'The Goat', 'The Harpy']

In [12]:
expected = set(range(29))
actual = {card["number"] for card in cards}

print("Missing:", sorted(expected - actual))

Missing: [2, 3, 4, 5, 6, 7, 8, 9]

In [13]:
import pandas as pd

cards = pd.read_csv("harpy_cards.csv")

cards.head()

,number,title,keywords,oracle,injury,disorientation,restoration,sovereignty,gift,lunar_day,lunar_phase,lunar_gate,theme,shadow
0,0,The Pearl,Potential|Void|Origin,Trust what is gestating. Not all treasures are...,Loss of possibility,Emptiness,Renewed potential,Self-authorship,Trust in becoming,Day 0,🌑 New Moon,Potential & Calling,Seed,Untapped potential
1,1,The Ear,Vibration|Sound|The Calling,What is being called into existence?,Missed opportunity,Uncertainty,Listening,Purposeful action,Discernment,Day 1,Waxing Crescent,Potential & Calling,Herald,Refusal to listen
2,2,The Inner Eye,Reflection|Duality|Awareness,What is being reflected back to you?,Self-deception,Confusion,Awareness,Clear perception,Insight,Day 2,Waxing Crescent,Potential & Calling,Witness,Self-deception
3,3,The Shattered Shell,Creation|Growth|Emergence,Honor the process of becoming.,Fear of change,Vulnerability,Emergence,Authentic identity,Courage,Day 3,Waxing Crescent,Potential & Calling,Growth,Fear of emergence
4,4,The Hearthstone,Foundation|Stability|Belonging,Strengthen your foundations.,Loss of belonging,Rootlessness,Stability,Inner security,Sanctuary,Day 4,Waxing Crescent,Potential & Calling,Guardian,Attachment to false security

In [14]:
cards.sample(5)[["title","theme","gift"]]

        title           theme          gift
20   The Well     Nourishment   Nourishment
7   The Satyr        Wanderer        Wonder
27   The Goat  Accomplishment    Confidence
8    The Cave      Initiation  Inner wisdom
10  The Wheel         Rebirth        Timing

In [15]:
from itertools import combinations

pairs = list(
    combinations(cards["title"], 2)
)

len(pairs)

406

In [16]:
pairs_df = pd.DataFrame(
    pairs,
    columns=["card1", "card2"]
)

pairs_df.head()

       card1                card2
0  The Pearl              The Ear
1  The Pearl        The Inner Eye
2  The Pearl  The Shattered Shell
3  The Pearl      The Hearthstone
4  The Pearl           The Selkie

In [17]:
pairs_df = pairs_df.merge(
    cards[["title","theme"]],
    left_on="card1",
    right_on="title"
).rename(columns={"theme":"theme1"}).drop(columns="title")

pairs_df = pairs_df.merge(
    cards[["title","theme"]],
    left_on="card2",
    right_on="title"
).rename(columns={"theme":"theme2"}).drop(columns="title")

In [18]:
pairs_df.head()

       card1                card2 theme1    theme2
0  The Pearl              The Ear   Seed    Herald
1  The Pearl        The Inner Eye   Seed   Witness
2  The Pearl  The Shattered Shell   Seed    Growth
3  The Pearl      The Hearthstone   Seed  Guardian
4  The Pearl           The Selkie   Seed     Exile

In [19]:
pairs_df["relationship_seed"] = (
    pairs_df["theme1"]
    + " → "
    + pairs_df["theme2"]
)

pairs_df[
    ["card1","card2","relationship_seed"]
].head(20)

        card1                card2     relationship_seed
0   The Pearl              The Ear         Seed → Herald
1   The Pearl        The Inner Eye        Seed → Witness
2   The Pearl  The Shattered Shell         Seed → Growth
3   The Pearl      The Hearthstone       Seed → Guardian
4   The Pearl           The Selkie          Seed → Exile
5   The Pearl            The Heart          Seed → Lover
6   The Pearl            The Satyr       Seed → Wanderer
7   The Pearl             The Cave     Seed → Initiation
8   The Pearl       The Bone Skull      Seed → Ancestors
9   The Pearl            The Wheel        Seed → Rebirth
10  The Pearl           The Mirror    Seed → Recognition
11  The Pearl              The Bat    Seed → Perspective
12  The Pearl            The Thorn         Seed → Wisdom
13  The Pearl            The Angel         Seed → Healer
14  The Pearl            The Torch          Seed → Power
15  The Pearl        The Lightning   Seed → Illumination
16  The Pearl         The Starling           Seed → Hope
17  The Pearl             The Moon   Seed → Subconscious
18  The Pearl              The Sun  Seed → Consciousness
19  The Pearl             The Well    Seed → Nourishment

In [20]:
cards["theme"].tolist()

['Seed',
 'Herald',
 'Witness',
 'Growth',
 'Guardian',
 'Exile',
 'Lover',
 'Wanderer',
 'Initiation',
 'Ancestors',
 'Rebirth',
 'Recognition',
 'Perspective',
 'Wisdom',
 'Healer',
 'Power',
 'Illumination',
 'Hope',
 'Subconscious',
 'Consciousness',
 'Nourishment',
 'Obstacles Overcome',
 'Responsibility',
 'Overview',
 'Flood',
 'Transformation',
 'Wholeness',
 'Accomplishment',
 'Sovereignty']

In [21]:
from itertools import combinations

pairs = pd.DataFrame(
    combinations(cards["theme"], 2),
    columns=["theme1","theme2"]
)

pairs.head()

  theme1    theme2
0   Seed    Herald
1   Seed   Witness
2   Seed    Growth
3   Seed  Guardian
4   Seed     Exile

In [22]:
pairs["relationship"] = (
    pairs["theme1"]
    + " → "
    + pairs["theme2"]
)

pairs.head()

  theme1    theme2     relationship
0   Seed    Herald    Seed → Herald
1   Seed   Witness   Seed → Witness
2   Seed    Growth    Seed → Growth
3   Seed  Guardian  Seed → Guardian
4   Seed     Exile     Seed → Exile

In [23]:
pairs.to_csv(
    "harpy_theme_relationships.csv",
    index=False
)

In [24]:
cards["theme"].tolist()

['Seed',
 'Herald',
 'Witness',
 'Growth',
 'Guardian',
 'Exile',
 'Lover',
 'Wanderer',
 'Initiation',
 'Ancestors',
 'Rebirth',
 'Recognition',
 'Perspective',
 'Wisdom',
 'Healer',
 'Power',
 'Illumination',
 'Hope',
 'Subconscious',
 'Consciousness',
 'Nourishment',
 'Obstacles Overcome',
 'Responsibility',
 'Overview',
 'Flood',
 'Transformation',
 'Wholeness',
 'Accomplishment',
 'Sovereignty']

In [25]:
theme_categories = {

    "Origins": [
        "Seed",
        "Herald",
        "Witness",
        "Growth",
        "Guardian"
    ],

    "Departure": [
        "Exile",
        "Lover",
        "Wanderer",
        "Initiation"
    ],

    "Descent": [
        "Ancestors",
        "Rebirth",
        "Recognition",
        "Perspective",
        "Wisdom"
    ],

    "Restoration": [
        "Healer",
        "Power",
        "Illumination",
        "Hope"
    ],

    "Integration": [
        "Subconscious",
        "Consciousness",
        "Nourishment"
    ],

    "Mastery": [
        "Obstacles Overcome",
        "Responsibility",
        "Overview"
    ],

    "Transformation": [
        "Flood",
        "Transformation",
        "Wholeness"
    ],

    "Sovereignty": [
        "Accomplishment",
        "Sovereignty"
    ]
}

In [26]:
rows = []

for category, themes in theme_categories.items():
    for theme in themes:
        rows.append({
            "category": category,
            "theme": theme
        })

theme_df = pd.DataFrame(rows)

theme_df

          category               theme
0          Origins                Seed
1          Origins              Herald
2          Origins             Witness
3          Origins              Growth
4          Origins            Guardian
5        Departure               Exile
6        Departure               Lover
7        Departure            Wanderer
8        Departure          Initiation
9          Descent           Ancestors
10         Descent             Rebirth
11         Descent         Recognition
12         Descent         Perspective
13         Descent              Wisdom
14     Restoration              Healer
15     Restoration               Power
16     Restoration        Illumination
17     Restoration                Hope
18     Integration        Subconscious
19     Integration       Consciousness
20     Integration         Nourishment
21         Mastery  Obstacles Overcome
22         Mastery      Responsibility
23         Mastery            Overview
24  Transformation               Flood
25  Transformation      Transformation
26  Transformation           Wholeness
27     Sovereignty      Accomplishment
28     Sovereignty         Sovereignty

In [27]:
theme_df.to_csv(
    "harpy_theme_categories.csv",
    index=False
)

In [28]:
cards = cards.merge(
    theme_df,
    on="theme",
    how="left"
)

In [29]:
cards[
    ["title","theme","category"]
]

                  title               theme        category
0             The Pearl                Seed         Origins
1               The Ear              Herald         Origins
2         The Inner Eye             Witness         Origins
3   The Shattered Shell              Growth         Origins
4       The Hearthstone            Guardian         Origins
5            The Selkie               Exile       Departure
6             The Heart               Lover       Departure
7             The Satyr            Wanderer       Departure
8              The Cave          Initiation       Departure
9        The Bone Skull           Ancestors         Descent
10            The Wheel             Rebirth         Descent
11           The Mirror         Recognition         Descent
12              The Bat         Perspective         Descent
13            The Thorn              Wisdom         Descent
14            The Angel              Healer     Restoration
15            The Torch               Power     Restoration
16        The Lightning        Illumination     Restoration
17         The Starling                Hope     Restoration
18             The Moon        Subconscious     Integration
19              The Sun       Consciousness     Integration
20             The Well         Nourishment     Integration
21         The Mountain  Obstacles Overcome         Mastery
22                Atlas      Responsibility         Mastery
23             The Hawk            Overview         Mastery
24            The Storm               Flood  Transformation
25          The Vulture      Transformation  Transformation
26     The Eye of Horus           Wholeness  Transformation
27             The Goat      Accomplishment     Sovereignty
28            The Harpy         Sovereignty     Sovereignty

In [30]:
flock = cards.sample(5).copy()

flock

,number,title,keywords,oracle,injury,disorientation,restoration,sovereignty,gift,lunar_day,lunar_phase,lunar_gate,theme,shadow,category
4,4,The Hearthstone,Foundation|Stability|Belonging,Strengthen your foundations.,Loss of belonging,Rootlessness,Stability,Inner security,Sanctuary,Day 4,Waxing Crescent,Potential & Calling,Guardian,Attachment to false security,Origins
22,22,Atlas,Responsibility|Endurance|Legacy,Carry only what is truly yours to bear.,Burden,Exhaustion,Boundaries,Stewardship,Endurance,Day 22,Full Moon Threshold,Mastery & Sovereignty,Responsibility,Carrying what is not yours,Mastery
15,15,The Torch,Power|Desire|Responsibility,Carry your fire wisely.,Powerlessness,Misdirected desire,Empowerment,Responsible power,Inspiration,Day 15,🌕 Full Moon Threshold,Challenge & Transformation,Power,Misuse of power,Restoration
2,2,The Inner Eye,Reflection|Duality|Awareness,What is being reflected back to you?,Self-deception,Confusion,Awareness,Clear perception,Insight,Day 2,Waxing Crescent,Potential & Calling,Witness,Self-deception,Origins
23,23,The Hawk,Vision|Clarity|Expansion,Rise above the situation and observe.,Narrow vision,Tunnel vision,Perspective,Strategic clarity,Foresight,Day 23,Full Moon Threshold,Mastery & Sovereignty,Overview,Detachment from human reality,Mastery

In [31]:
flock["category"].value_counts()

category
Origins        2
Mastery        2
Restoration    1
Name: count, dtype: int64

In [32]:
positions = [
    "The Wound",
    "What Was Lost",
    "What Watches Over You",
    "What Must Be Reclaimed",
    "The Harpy's Gift"
]

flock = flock.reset_index(drop=True)

flock["position"] = positions

In [33]:
flock[
    [
        "position",
        "title",
        "theme",
        "injury",
        "restoration",
        "gift"
    ]
]

,position,title,theme,injury,restoration,gift
0,The Wound,The Hearthstone,Guardian,Loss of belonging,Stability,Sanctuary
1,What Was Lost,Atlas,Responsibility,Burden,Boundaries,Endurance
2,What Watches Over You,The Torch,Power,Powerlessness,Empowerment,Inspiration
3,What Must Be Reclaimed,The Inner Eye,Witness,Self-deception,Awareness,Insight
4,The Harpy's Gift,The Hawk,Overview,Narrow vision,Perspective,Foresight

In [34]:
category_counts = flock["category"].value_counts()

dominant = category_counts.idxmax()

print(
    f"This flock is dominated by {dominant} energy."
)

This flock is dominated by Origins energy.

In [35]:
flock.columns.tolist()

['number',
 'title',
 'keywords',
 'oracle',
 'injury',
 'disorientation',
 'restoration',
 'sovereignty',
 'gift',
 'lunar_day',
 'lunar_phase',
 'lunar_gate',
 'theme',
 'shadow',
 'category',
 'position']

In [36]:
flock[
    [
        "position",
        "title",
        "theme",
        "injury",
        "disorientation",
        "shadow",
        "restoration",
        "sovereignty",
        "gift",
        "category"
    ]
]

,position,title,theme,injury,disorientation,shadow,restoration,sovereignty,gift,category
0,The Wound,The Hearthstone,Guardian,Loss of belonging,Rootlessness,Attachment to false security,Stability,Inner security,Sanctuary,Origins
1,What Was Lost,Atlas,Responsibility,Burden,Exhaustion,Carrying what is not yours,Boundaries,Stewardship,Endurance,Mastery
2,What Watches Over You,The Torch,Power,Powerlessness,Misdirected desire,Misuse of power,Empowerment,Responsible power,Inspiration,Restoration
3,What Must Be Reclaimed,The Inner Eye,Witness,Self-deception,Confusion,Self-deception,Awareness,Clear perception,Insight,Origins
4,The Harpy's Gift,The Hawk,Overview,Narrow vision,Tunnel vision,Detachment from human reality,Perspective,Strategic clarity,Foresight,Mastery

In [37]:
flock["category"].value_counts()

category
Origins        2
Mastery        2
Restoration    1
Name: count, dtype: int64

In [38]:
wound = flock.iloc[0]
lost = flock.iloc[1]
guide = flock.iloc[2]
reclaim = flock.iloc[3]
gift = flock.iloc[4]

print(f"""
THE HARPIES SAY

The wound appears as {wound['title']}.

This suggests an injury related to:
{wound['injury']}.

The resulting disorientation may feel like:
{wound['disorientation']}.

What was lost is reflected by {lost['title']}.

Yet {guide['title']} watches over you,
offering the gift of {guide['gift']}.

What must be reclaimed is
{reclaim['sovereignty']}.

The Harpy's Gift arrives through
{gift['gift']}.

Restoration remains possible,
even when justice never arrived.
""")

THE HARPIES SAY

The wound appears as The Hearthstone.

This suggests an injury related to:
Loss of belonging.

The resulting disorientation may feel like:
Rootlessness.

What was lost is reflected by Atlas.

Yet The Torch watches over you,
offering the gift of Inspiration.

What must be reclaimed is
Clear perception.

The Harpy's Gift arrives through
Foresight.

Restoration remains possible,
even when justice never arrived.

In [39]:
import pandas as pd

cards = pd.read_csv("harpy_cards.csv")

cards[["number","title","keywords","oracle"]].head()

,number,title,keywords,oracle
0,0,The Pearl,Potential|Void|Origin,Trust what is gestating. Not all treasures are...
1,1,The Ear,Vibration|Sound|The Calling,What is being called into existence?
2,2,The Inner Eye,Reflection|Duality|Awareness,What is being reflected back to you?
3,3,The Shattered Shell,Creation|Growth|Emergence,Honor the process of becoming.
4,4,The Hearthstone,Foundation|Stability|Belonging,Strengthen your foundations.

In [40]:
print(len(cards))

29

In [41]:
cards.columns.tolist()

['number',
 'title',
 'keywords',
 'oracle',
 'injury',
 'disorientation',
 'restoration',
 'sovereignty',
 'gift',
 'lunar_day',
 'lunar_phase',
 'lunar_gate',
 'theme',
 'shadow']

In [42]:
import pandas as pd

cards = pd.read_csv("harpy_cards_meanings.csv")

print(len(cards))
cards.columns.tolist()

29

['number',
 'title',
 'keywords',
 'meaning',
 'oracle',
 'injury',
 'disorientation',
 'restoration',
 'sovereignty',
 'gift',
 'lunar_day',
 'lunar_phase',
 'lunar_gate',
 'theme',
 'shadow']

In [43]:
cards["image"] = cards.apply(
    lambda row:
        f"{int(row['number']):02d}-"
        + row["title"]
            .lower()
            .replace(" ", "-")
            .replace("'", "")
        + ".png",
    axis=1
)

cards[["number","title","image"]].head(10)

   number                title                       image
0       0            The Pearl            00-the-pearl.png
1       1              The Ear              01-the-ear.png
2       2        The Inner Eye        02-the-inner-eye.png
3       3  The Shattered Shell  03-the-shattered-shell.png
4       4      The Hearthstone      04-the-hearthstone.png
5       5           The Selkie           05-the-selkie.png
6       6            The Heart            06-the-heart.png
7       7            The Satyr            07-the-satyr.png
8       8             The Cave             08-the-cave.png
9       9       The Bone Skull       09-the-bone-skull.png

In [44]:
import json

website_cards = cards[
    [
        "number",
        "title",
        "keywords",
        "oracle",
        "meaning",
        "image"
    ]
].copy()

website_cards["keywords"] = (
    website_cards["keywords"]
    .fillna("")
    .str.split("|")
)

with open(
    "../the-oracle-of-harpies/cards.json",
    "w",
    encoding="utf-8"
) as f:
    json.dump(
        website_cards.to_dict("records"),
        f,
        indent=2,
        ensure_ascii=False
    )

print("Created cards.json with", len(website_cards), "cards")

Created cards.json with 29 cards

In [45]:
cards[["number","title","image"]].tail()

    number             title                    image
24      24         The Storm         24-the-storm.png
25      25       The Vulture       25-the-vulture.png
26      26  The Eye of Horus  26-the-eye-of-horus.png
27      27          The Goat          27-the-goat.png
28      28         The Harpy         28-the-harpy.png